### ISSUE TITLE
pbxproj-dom is not compatible with regular JS / node due to a package.json issue

### ISSUE THREAD

**Issue by RyanCopley** [PanayotCankov/pbxproj-dom#1]
https://github.com/PanayotCankov/pbxproj-dom/blob/master/package.json#L5

There is no index.js file (or ts file), making this module unusable in regular Node v6. I'm going to try to figure out what it should be and open a PR.

**Comment by RyanCopley** [comment]
I don't know what files are public facing, but my requirements can be met with:

```javascript
"use strict";
module.exports = {
  Xcode : require("./xcode").Xcode
};
```

**Comment by PanayotCankov** [comment]
It is supposed to be required using `var xcode = require("pbxproj-dom/xcode");`, there are 3 layers in the same module I am not sure which should be made public at the moment. The main entry in the package json is truly redundant :( if the package gets broader adoption I will clean it up or at least re-export the Xcode.
